site_name: Telegramia
site_url: https://mezgoodle.github.io/TelegramiaSite/
site_description: Telegramia is the text-based game in Telegram
site_author: mezgoodle
copyright: © 2022 mezgoodle
nav:
  - Home: index.md
  - Telegramia group: group.md
  - Telegramia:
      - Introduction: telegramia/index.md
      - Manual: telegramia/manual.md
      - Technical detail: telegramia/technical.md
  - Telegramia API:
      - Introduction: api/index.md
      - Technical detail: api/technical.md
  - Telegramia Stats:
      - Introduction: stats/index.md
      - Technical detail: stats/technical.md
  - Telegramia Site:
      - Introduction: site/index.md
      - Technical detail: site/technical.md
theme:
  name: material
  locale: en
  palette:
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
  icon:
    repo: fontawesome/brands/github
repo_name: mezgoodle/TelegramiaSite
repo_url: https://github.com/mezgoodle/TelegramiaSite
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
